### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by hsiaoyi0504** [WMBEdmands/compMS2Miner#2]
Hi, when I installed this package using `devtools::install_github('WMBEdmands/compMS2Miner', dependencies=c("Depends", "Imports", "Suggests"), build_vignettes=TRUE)`. It can't install `mzR`.
I think maybe it's because `mzR` is under Bioconductor. However, I am not familiar enough with R. I can't provide a PR for that.

**Comment by WMBEdmands** [comment]
Hi, what was the specific error message? I did a Google search and it appears others have had a similar issue installing mzR. 
Perhaps try installing mzR separately before installing compMS2Miner:
biocLite('mzR')
Let me know if this resolves the problem.

**Comment by hsiaoyi0504** [comment]
The message showed is
`ERROR: dependency 'mzR' is not available for package 'compMS2Miner'`

**Comment by hsiaoyi0504** [comment]
I found that I also can't install `mzR` separately through `biocLite('mzR')`.
It shows that `ERROR: compilation failed for package 'mzR'`.
Maybe it's where the issue comes from.

**Comment by hsiaoyi0504** [comment]
It is related to sneumann/mzR#85

**Comment by hsiaoyi0504** [comment]
It finally resolved ! It's `homebew`'s problem when installing `netCDF`

**Comment by WMBEdmands** [comment]
I wasn't sure what to suggest. I remember I also had trouble installing mzR on Linux-based servers before. I'm glad you fixed the problem.
